name: aliyunpan_api
description: 阿里云盘开放平台接口.
version: 1.0.5
homepage: https://github.com/sososdk/aliyunpan-flutter-sdk
repository: https://github.com/sososdk/aliyunpan-flutter-sdk/tree/master/aliyunpan_api

environment:
  sdk: ^3.3.4

dependencies:
  path: ^1.9.1
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
