name: aliyunpan_api
description: 阿里云盘开放平台接口.
version: 1.0.4
homepage: https://github.com/sososdk/aliyunpan-flutter-sdk
repository: https://github.com/sososdk/aliyunpan-flutter-sdk/tree/master/aliyunpan_api

environment:
  sdk: ^3.3.4

dependencies:
  path: ^1.9.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
