name: aliyunpan_sdk
description: 阿里云盘开放平台 SDK.
version: 1.0.1
homepage: https://github.com/sososdk/aliyunpan-flutter-sdk
repository: https://github.com/sososdk/aliyunpan-flutter-sdk/tree/master/aliyunpan_sdk

environment:
  sdk: ^3.3.4

dependencies:
   dio: ^5.4.3+1
   anio: ^2.0.2
   crypto: ^3.0.3
   collection: ^1.18.0
   aliyunpan_api: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
